package me.kaelaela.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.kaelaela.dao.Memo;
import me.kaelaela.dao.Editor;

import me.kaelaela.dao.MemoDao;
import me.kaelaela.dao.EditorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoDaoConfig;
    private final DaoConfig editorDaoConfig;

    private final MemoDao memoDao;
    private final EditorDao editorDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoDaoConfig = daoConfigMap.get(MemoDao.class).clone();
        memoDaoConfig.initIdentityScope(type);

        editorDaoConfig = daoConfigMap.get(EditorDao.class).clone();
        editorDaoConfig.initIdentityScope(type);

        memoDao = new MemoDao(memoDaoConfig, this);
        editorDao = new EditorDao(editorDaoConfig, this);

        registerDao(Memo.class, memoDao);
        registerDao(Editor.class, editorDao);
    }
    
    public void clear() {
        memoDaoConfig.clearIdentityScope();
        editorDaoConfig.clearIdentityScope();
    }

    public MemoDao getMemoDao() {
        return memoDao;
    }

    public EditorDao getEditorDao() {
        return editorDao;
    }

}
