package me.kaelaela.dao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import me.kaelaela.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "EDITOR".
 */
@Entity(active = true)
public class Editor {

    @Id
    @Unique
    @Index
    private long id;
    private String name;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient EditorDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "id")
    })
    @OrderBy("editDate ASC")
    private List<Memo> memos;

    @Generated
    public Editor() {
    }

    public Editor(long id) {
        this.id = id;
    }

    @Generated
    public Editor(long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEditorDao() : null;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Memo> getMemos() {
        if (memos == null) {
            __throwIfDetached();
            MemoDao targetDao = daoSession.getMemoDao();
            List<Memo> memosNew = targetDao._queryEditor_Memos(id);
            synchronized (this) {
                if(memos == null) {
                    memos = memosNew;
                }
            }
        }
        return memos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetMemos() {
        memos = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
