package me.kaelaela.dao;

import me.kaelaela.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEMO".
 */
public class Memo {

    private Long id;
    private String content;
    private java.util.Date editDate;
    private Boolean isDone;
    private long editorId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MemoDao myDao;

    private Editor editor;
    private Long editor__resolvedKey;


    public Memo() {
    }

    public Memo(Long id) {
        this.id = id;
    }

    public Memo(Long id, String content, java.util.Date editDate, Boolean isDone, long editorId) {
        this.id = id;
        this.content = content;
        this.editDate = editDate;
        this.isDone = isDone;
        this.editorId = editorId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMemoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getEditDate() {
        return editDate;
    }

    public void setEditDate(java.util.Date editDate) {
        this.editDate = editDate;
    }

    public Boolean getIsDone() {
        return isDone;
    }

    public void setIsDone(Boolean isDone) {
        this.isDone = isDone;
    }

    public long getEditorId() {
        return editorId;
    }

    public void setEditorId(long editorId) {
        this.editorId = editorId;
    }

    /** To-one relationship, resolved on first access. */
    public Editor getEditor() {
        long __key = this.editorId;
        if (editor__resolvedKey == null || !editor__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            EditorDao targetDao = daoSession.getEditorDao();
            Editor editorNew = targetDao.load(__key);
            synchronized (this) {
                editor = editorNew;
            	editor__resolvedKey = __key;
            }
        }
        return editor;
    }

    public void setEditor(Editor editor) {
        if (editor == null) {
            throw new DaoException("To-one property 'editorId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.editor = editor;
            editorId = editor.getId();
            editor__resolvedKey = editorId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
