package me.kaelaela.dao;

import org.greenrobot.greendao.annotation.*;

import me.kaelaela.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEMO".
 */
@Entity(active = true)
public class Memo {

    @Id
    @Unique
    @Index
    private Long id;
    private String content;
    private java.util.Date editDate;
    private Boolean isDone;
    private long editorId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient MemoDao myDao;

    @ToOne(joinProperty = "editorId")
    private Editor editor;

    @Generated
    private transient Long editor__resolvedKey;

    @Generated
    public Memo() {
    }

    public Memo(Long id) {
        this.id = id;
    }

    @Generated
    public Memo(Long id, String content, java.util.Date editDate, Boolean isDone, long editorId) {
        this.id = id;
        this.content = content;
        this.editDate = editDate;
        this.isDone = isDone;
        this.editorId = editorId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMemoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getEditDate() {
        return editDate;
    }

    public void setEditDate(java.util.Date editDate) {
        this.editDate = editDate;
    }

    public Boolean getIsDone() {
        return isDone;
    }

    public void setIsDone(Boolean isDone) {
        this.isDone = isDone;
    }

    public long getEditorId() {
        return editorId;
    }

    public void setEditorId(long editorId) {
        this.editorId = editorId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Editor getEditor() {
        long __key = this.editorId;
        if (editor__resolvedKey == null || !editor__resolvedKey.equals(__key)) {
            __throwIfDetached();
            EditorDao targetDao = daoSession.getEditorDao();
            Editor editorNew = targetDao.load(__key);
            synchronized (this) {
                editor = editorNew;
            	editor__resolvedKey = __key;
            }
        }
        return editor;
    }

    @Generated
    public void setEditor(Editor editor) {
        if (editor == null) {
            throw new DaoException("To-one property 'editorId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.editor = editor;
            editorId = editor.getId();
            editor__resolvedKey = editorId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
