package me.kaelaela.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEMO".
*/
public class MemoDao extends AbstractDao<Memo, Long> {

    public static final String TABLENAME = "MEMO";

    /**
     * Properties of entity Memo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property EditDate = new Property(2, java.util.Date.class, "editDate", false, "EDIT_DATE");
        public final static Property IsDone = new Property(3, Boolean.class, "isDone", false, "IS_DONE");
        public final static Property EditorId = new Property(4, long.class, "editorId", false, "EDITOR_ID");
    }

    private DaoSession daoSession;

    private Query<Memo> editor_MemosQuery;

    public MemoDao(DaoConfig config) {
        super(config);
    }
    
    public MemoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEMO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: id
                "\"CONTENT\" TEXT," + // 1: content
                "\"EDIT_DATE\" INTEGER," + // 2: editDate
                "\"IS_DONE\" INTEGER," + // 3: isDone
                "\"EDITOR_ID\" INTEGER NOT NULL );"); // 4: editorId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_MEMO__id ON MEMO" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEMO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Memo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        java.util.Date editDate = entity.getEditDate();
        if (editDate != null) {
            stmt.bindLong(3, editDate.getTime());
        }
 
        Boolean isDone = entity.getIsDone();
        if (isDone != null) {
            stmt.bindLong(4, isDone ? 1L: 0L);
        }
        stmt.bindLong(5, entity.getEditorId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Memo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        java.util.Date editDate = entity.getEditDate();
        if (editDate != null) {
            stmt.bindLong(3, editDate.getTime());
        }
 
        Boolean isDone = entity.getIsDone();
        if (isDone != null) {
            stmt.bindLong(4, isDone ? 1L: 0L);
        }
        stmt.bindLong(5, entity.getEditorId());
    }

    @Override
    protected final void attachEntity(Memo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Memo readEntity(Cursor cursor, int offset) {
        Memo entity = new Memo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // editDate
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isDone
            cursor.getLong(offset + 4) // editorId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Memo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEditDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setIsDone(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setEditorId(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Memo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Memo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Memo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "memos" to-many relationship of Editor. */
    public List<Memo> _queryEditor_Memos(Long id) {
        synchronized (this) {
            if (editor_MemosQuery == null) {
                QueryBuilder<Memo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                queryBuilder.orderRaw("T.'EDIT_DATE' ASC");
                editor_MemosQuery = queryBuilder.build();
            }
        }
        Query<Memo> query = editor_MemosQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEditorDao().getAllColumns());
            builder.append(" FROM MEMO T");
            builder.append(" LEFT JOIN EDITOR T0 ON T.\"EDITOR_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Memo loadCurrentDeep(Cursor cursor, boolean lock) {
        Memo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Editor editor = loadCurrentOther(daoSession.getEditorDao(), cursor, offset);
         if(editor != null) {
            entity.setEditor(editor);
        }

        return entity;    
    }

    public Memo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Memo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Memo> list = new ArrayList<Memo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Memo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Memo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
